<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>Tenon.Update</RootNamespace>
    <PackageId>Tenon.Update</PackageId>
    <Description>Check for, download and apply updates of applications installed with Tenon.</Description>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Microsoft.Win32.Registry" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
  </ItemGroup>
</Project>
