using System.ComponentModel;
using System.Text.Json.Serialization;

namespace Tenon.Core.Model;

/// <summary>Root of a tenon.json file.</summary>
public sealed class InstallerDefinition
{
    [JsonPropertyName("$schema")] public string? Schema { get; set; }

    [Description("How the application is built and published before packaging.")]
    public BuildSection Build { get; set; } = new();

    [Description("Product identity shown in Add/Remove Programs and used for upgrades.")]
    public ProductSection Product { get; set; } = new();

    [Description("Where and how the product is installed.")]
    public InstallSection Install { get; set; } = new();

    [Description("Files and folders to install. Globs are supported.")]
    public List<FileRule> Files { get; set; } = new();

    [Description("Start Menu, Desktop and Startup shortcuts.")]
    public List<ShortcutDef> Shortcuts { get; set; } = new();

    [Description("Optional checkboxes shown on the Options page. Each task becomes a feature.")]
    public List<TaskDef> Tasks { get; set; } = new();

    [Description("File extensions registered for the application.")]
    public List<FileAssociationDef> FileAssociations { get; set; } = new();

    [Description("Registry values written at install and removed at uninstall.")]
    public List<RegistryDef> Registry { get; set; } = new();

    [Description("Environment variables set, appended or removed.")]
    public List<EnvironmentDef> Environment { get; set; } = new();

    [Description("Windows services installed with the product.")]
    public List<ServiceDef> Services { get; set; } = new();

    [Description("Windows Firewall exceptions.")]
    public List<FirewallDef> Firewall { get; set; } = new();

    [Description("Runtimes and packages that must be present before the product installs.")]
    public List<PrerequisiteDef> Prerequisites { get; set; } = new();

    [Description("C# setup hooks that run during install and uninstall.")]
    public HooksSection? Hooks { get; set; }

    [Description("Look and flow of the Setup.exe user interface.")]
    public UiSection Ui { get; set; } = new();

    [Description("Code signing configuration.")]
    public SigningSection Signing { get; set; } = new();

    [Description("Auto-update feed used by the Tenon.Update runtime.")]
    public UpdateSection? Update { get; set; }

    [Description("Output file names and locations.")]
    public OutputSection Output { get; set; } = new();
}

public sealed class BuildSection
{
    [Description("Path to the application project (.csproj) to publish. Relative to tenon.json.")]
    public string? Project { get; set; }

    [Description("Build configuration passed to dotnet publish. Default: Release.")]
    public string Configuration { get; set; } = "Release";

    [Description("Runtime identifier passed to dotnet publish. Default derived from product.arch (win-x64).")]
    public string? RuntimeIdentifier { get; set; }

    [Description("Publish the application self-contained (bundles the .NET runtime).")]
    public bool SelfContained { get; set; }

    [Description("Extra arguments appended to dotnet publish.")]
    public string? PublishArgs { get; set; }

    [Description("Use an existing publish folder instead of running dotnet publish. Relative to tenon.json.")]
    public string? PublishDir { get; set; }
}

public sealed class ProductSection
{
    [Description("Product name shown to users and in Add/Remove Programs.")]
    public string Name { get; set; } = "";

    [Description("Product version. Use $(AssemblyVersion) to take it from the main executable.")]
    public string Version { get; set; } = "$(AssemblyVersion)";

    [Description("Company or publisher name.")]
    public string Publisher { get; set; } = "";

    [Description("Stable GUID that identifies the product family across versions. Generated by tenon init.")]
    public string? UpgradeCode { get; set; }

    [Description("Short description shown in Add/Remove Programs.")]
    public string? Description { get; set; }

    [Description("Product web site.")]
    public string? Url { get; set; }

    [Description("Support web site.")]
    public string? SupportUrl { get; set; }

    [Description("Path to an .ico file used for Add/Remove Programs and the setup window.")]
    public string? Icon { get; set; }

    [Description("Languages of the installer. The first is the default; others are embedded as transforms.")]
    public List<string> Languages { get; set; } = new() { "en-US" };

    [Description("Target architecture: x64, x86 or arm64.")]
    public Architecture Arch { get; set; } = Architecture.X64;

    [Description("Allow re-installing the same version over itself as a major upgrade. Default false.")]
    public bool AllowSameVersionUpgrades { get; set; }
}

public sealed class InstallSection
{
    [Description("perMachine (Program Files, admin), perUser (no admin) or either (user chooses).")]
    public InstallScope Scope { get; set; } = InstallScope.Either;

    [Description("Default scope when scope is 'either'.")]
    public InstallScope DefaultScope { get; set; } = InstallScope.PerUser;

    [Description("Installation folder, e.g. {autopf}\\Company\\Product. Becomes {app}.")]
    public string Dir { get; set; } = "{autopf}\\$(Publisher)\\$(ProductName)";

    [Description("Let the user change the installation folder.")]
    public bool AllowChangeDir { get; set; } = true;

    [Description("Minimum Windows version, e.g. 10.0.17763.")]
    public string? MinWindows { get; set; }

    [Description("Main executable file name inside {app}. Used for shortcuts, close-app detection and run-after-install.")]
    public string? MainExe { get; set; }

    [Description("What to do when the application is running during install: prompt, force or fail.")]
    public CloseRunningAppMode CloseRunningApp { get; set; } = CloseRunningAppMode.Prompt;

    [Description("Offer to launch the application when setup finishes.")]
    public bool RunAfterInstall { get; set; } = true;

    [Description("Folders deleted on uninstall (user data), e.g. {localappdata}\\Company\\Product.")]
    public List<string> DeleteAppDataOnUninstall { get; set; } = new();

    [Description("Add/Remove Programs options.")]
    public ArpSection Arp { get; set; } = new();
}

public sealed class ArpSection
{
    [Description("Hide the Modify button.")]
    public bool NoModify { get; set; }

    [Description("Hide the Repair button.")]
    public bool NoRepair { get; set; }

    [Description("Hide the product from Add/Remove Programs entirely.")]
    public bool Hidden { get; set; }
}

public sealed class FileRule
{
    [Description("Source path or glob, e.g. {publish}\\** or docs\\readme.txt. Relative to tenon.json.")]
    public string From { get; set; } = "";

    [Description("Glob patterns to exclude, e.g. *.pdb.")]
    public List<string> Exclude { get; set; } = new();

    [Description("Target folder, e.g. {app} or {app}\\plugins.")]
    public string To { get; set; } = "{app}";

    [Description("Never remove these files on uninstall.")]
    public bool Permanent { get; set; }

    [Description("Only install when this task is selected.")]
    public string? Task { get; set; }

    [Description("Raw MSI condition for advanced scenarios.")]
    public string? Condition { get; set; }
}

public sealed class ShortcutDef
{
    [Description("Shortcut display name.")]
    public string Name { get; set; } = "";

    [Description("Target file, e.g. {app}\\MyApp.exe.")]
    public string Target { get; set; } = "";

    [Description("Folder: {group} (Start Menu), {desktop} or {startup}.")]
    public string In { get; set; } = "{group}";

    [Description("Optional icon file, e.g. {app}\\MyApp.exe or {app}\\icon.ico.")]
    public string? Icon { get; set; }

    [Description("Icon index inside the icon file.")]
    public int IconIndex { get; set; }

    [Description("Command line arguments.")]
    public string? Args { get; set; }

    [Description("Working directory. Defaults to the folder of the target.")]
    public string? WorkingDir { get; set; }

    [Description("Tooltip description.")]
    public string? Description { get; set; }

    [Description("Only create when this task is selected.")]
    public string? Task { get; set; }
}

public sealed class TaskDef
{
    [Description("Identifier referenced by other elements (letters, digits, underscore).")]
    public string Id { get; set; } = "";

    [Description("Checkbox text.")]
    public string Title { get; set; } = "";

    [Description("Longer description.")]
    public string? Description { get; set; }

    [Description("Checked by default.")]
    public bool Default { get; set; } = true;
}

public sealed class FileAssociationDef
{
    [Description("Extension including the dot, e.g. .cnote.")]
    public string Extension { get; set; } = "";

    [Description("ProgId, e.g. Contoso.Notes.Document.")]
    public string ProgId { get; set; } = "";

    [Description("Friendly type name shown in Explorer.")]
    public string? Description { get; set; }

    [Description("Icon, e.g. {app}\\MyApp.exe,1.")]
    public string? Icon { get; set; }

    [Description("Open command, e.g. \"{app}\\MyApp.exe\" \"%1\".")]
    public string Open { get; set; } = "";

    [Description("MIME type.")]
    public string? Mime { get; set; }

    [Description("Only register when this task is selected.")]
    public string? Task { get; set; }
}

public sealed class RegistryDef
{
    [Description("HKMU (HKLM or HKCU depending on scope), HKLM, HKCU, HKCR or HKU.")]
    public RegistryRoot Root { get; set; } = RegistryRoot.HKMU;

    [Description("Key path, e.g. Software\\Company\\Product.")]
    public string Key { get; set; } = "";

    [Description("Value name. Omit for the default value.")]
    public string? Name { get; set; }

    [Description("Value type: string, expandString, dword, qword, binary, multiString.")]
    public RegistryValueType Type { get; set; } = RegistryValueType.String;

    [Description("Value. Supports {app} and other constants.")]
    public string? Value { get; set; }

    [Description("Only write when this task is selected.")]
    public string? Task { get; set; }
}

public sealed class EnvironmentDef
{
    [Description("Variable name.")]
    public string Name { get; set; } = "";

    [Description("Value. Supports {app}.")]
    public string Value { get; set; } = "";

    [Description("set, append, prepend or remove.")]
    public EnvironmentAction Action { get; set; } = EnvironmentAction.Set;

    [Description("auto (follows install scope), user or machine.")]
    public EnvironmentScope Scope { get; set; } = EnvironmentScope.Auto;

    [Description("Only apply when this task is selected.")]
    public string? Task { get; set; }
}

public sealed class ServiceDef
{
    [Description("Service name (internal).")]
    public string Name { get; set; } = "";

    [Description("Display name.")]
    public string? DisplayName { get; set; }

    [Description("Description.")]
    public string? Description { get; set; }

    [Description("Executable, e.g. {app}\\MyService.exe.")]
    public string Exe { get; set; } = "";

    [Description("Command line arguments.")]
    public string? Args { get; set; }

    [Description("auto, demand, disabled or delayedAuto.")]
    public ServiceStartMode Start { get; set; } = ServiceStartMode.Auto;

    [Description("Account: LocalSystem, LocalService, NetworkService or a user name.")]
    public string Account { get; set; } = "LocalSystem";

    [Description("Account password (use a build macro; never commit secrets).")]
    public string? Password { get; set; }

    [Description("Start the service at the end of installation.")]
    public bool StartOnInstall { get; set; } = true;

    [Description("Stop the service before uninstall/upgrade.")]
    public bool StopOnUninstall { get; set; } = true;

    [Description("Service dependencies.")]
    public List<string> Dependencies { get; set; } = new();

    [Description("Recovery actions.")]
    public ServiceRecoveryDef? Recovery { get; set; }

    [Description("Requires a per-machine install (services always do).")]
    public ScopeRequirement Requires { get; set; } = ScopeRequirement.PerMachine;
}

public sealed class ServiceRecoveryDef
{
    [Description("Action on first failure: restart, none, reboot, runCommand.")]
    public string FirstFailure { get; set; } = "restart";
    public string SecondFailure { get; set; } = "restart";
    public string SubsequentFailures { get; set; } = "restart";
    [Description("Seconds before the failure count resets.")]
    public int ResetPeriod { get; set; } = 86400;
    [Description("Milliseconds to wait before restarting.")]
    public int RestartDelay { get; set; } = 60000;
}

public sealed class FirewallDef
{
    [Description("Rule name.")]
    public string Name { get; set; } = "";
    [Description("Program path, e.g. {app}\\MyApp.exe.")]
    public string? Program { get; set; }
    public FirewallDirection Direction { get; set; } = FirewallDirection.In;
    public FirewallProtocol Protocol { get; set; } = FirewallProtocol.Any;
    [Description("Port or port range, e.g. 8080 or 8000-8010.")]
    public string? Port { get; set; }
    [Description("Profiles: domain, private, public. Default: all.")]
    public List<string> Profiles { get; set; } = new();
    public ScopeRequirement Requires { get; set; } = ScopeRequirement.PerMachine;
}

public sealed class PrerequisiteDef
{
    [Description("Built-in id (dotnet-desktop, dotnet-runtime, vcredist-x64, vcredist-x86, vcredist-arm64) or a custom id.")]
    public string Id { get; set; } = "";
    [Description("Version, e.g. 8.0 for .NET or 14.30 for VC++.")]
    public string? Version { get; set; }
    [Description("Roll-forward policy for .NET: latestPatch, latestMinor, latestMajor.")]
    public string? RollForward { get; set; }
    [Description("Download the package at install time instead of embedding it.")]
    public bool Download { get; set; }
    [Description("Custom package file (msi or exe). Relative to tenon.json.")]
    public string? File { get; set; }
    [Description("Arguments for a custom exe package.")]
    public string? Args { get; set; }
    [Description("Detection for custom packages.")]
    public PrerequisiteDetectDef? Detect { get; set; }
    public ScopeRequirement Requires { get; set; } = ScopeRequirement.Any;
}

public sealed class PrerequisiteDetectDef
{
    [Description("Installed MSI product code.")]
    public string? ProductCode { get; set; }
    [Description("MSI upgrade code (any version).")]
    public string? UpgradeCode { get; set; }
    [Description("Registry value that must exist, e.g. HKLM\\Software\\Vendor\\Product\\Version.")]
    public string? RegistryValue { get; set; }
    [Description("Minimum value for registryValue.")]
    public string? MinVersion { get; set; }
    [Description("File that must exist.")]
    public string? File { get; set; }
}

public sealed class HooksSection
{
    [Description("Hooks project (.csproj) that references Tenon.Hooks. Relative to tenon.json.")]
    public string? Project { get; set; }
    [Description("Prebuilt hooks assembly instead of a project.")]
    public string? Assembly { get; set; }
    [Description("Where the hook host finds a .NET runtime: 'shared' (machine runtime) or 'app' (self-contained app folder).")]
    public string Runtime { get; set; } = "shared";
}

public sealed class UiSection
{
    [Description("modern (wizard pages) or oneClick (splash and progress only).")]
    public UiStyle Style { get; set; } = UiStyle.Modern;
    [Description("Page order. Available: welcome, license, scope, folder, options, progress, finish.")]
    public List<string> Pages { get; set; } = new() { "welcome", "license", "folder", "options", "progress", "finish" };
    [Description("License file (.rtf or .txt). Relative to tenon.json.")]
    public string? License { get; set; }
    public UiThemeSection Theme { get; set; } = new();
    [Description("Strings override file pattern, e.g. setup-strings.{lang}.json.")]
    public string? Strings { get; set; }
}

public sealed class UiThemeSection
{
    [Description("Accent color, e.g. #2563EB.")]
    public string Accent { get; set; } = "#2563EB";
    [Description("Window background color.")]
    public string? Background { get; set; }
    [Description("auto, light or dark.")]
    public string DarkMode { get; set; } = "auto";
    [Description("Logo image (png). Relative to tenon.json.")]
    public string? Logo { get; set; }
    [Description("Banner image shown on the welcome page.")]
    public string? Banner { get; set; }
    [Description("Font family.")]
    public string? Font { get; set; }
}

public sealed class SigningSection
{
    public SigningMode Mode { get; set; } = SigningMode.None;
    public SigningCertificateDef? Certificate { get; set; }
    [Description("RFC 3161 timestamp server URL.")]
    public string TimestampUrl { get; set; } = "http://timestamp.digicert.com";
    [Description("Command template used when mode is 'command'. {file} and {ts} are replaced.")]
    public string? Command { get; set; }
}

public sealed class SigningCertificateDef
{
    [Description("Certificate thumbprint in the current user or machine store.")]
    public string? Thumbprint { get; set; }
    [Description("PFX file path.")]
    public string? File { get; set; }
    [Description("Environment variable holding the PFX password.")]
    public string? PasswordEnv { get; set; }
}

public sealed class UpdateSection
{
    [Description("Feed URL. {channel} is replaced by the channel name.")]
    public string Feed { get; set; } = "";
    public string Channel { get; set; } = "stable";
    [Description("Generate delta packages when possible.")]
    public bool Delta { get; set; }
}

public sealed class OutputSection
{
    [Description("Output folder. Relative to tenon.json.")]
    public string Dir { get; set; } = "artifacts\\installer";
    [Description("MSI file name pattern.")]
    public string Msi { get; set; } = "$(ProductName)-$(Version)-$(Arch).msi";
    [Description("Setup.exe file name pattern.")]
    public string Setup { get; set; } = "$(ProductName)-Setup-$(Version).exe";
    [Description("Also keep the standalone MSI next to Setup.exe (for IT deployment).")]
    public bool ExtraMsi { get; set; } = true;
}
